### Simulation Params
pybullet_config:
  use_gui: False
  real_time_simulation: False
  gravity: [0.0, 0.0, 0.0] # [0.0, 0.0, -9.81]
  dt: 0.005

### Limb Repo Params
active_base_pose: [0.8, -0.1, 0.5, 0, 0, 1, 0] # x y z, euler x y z
active_q: [-0.32841343,  0.28639087, -1.99012555, -1.88232461,  1.32335729, -0.00612142]
active_urdf: "assets/urdf/franka6/panda.urdf"
active_joint_max: [2.8973, 1.7628, -0.0698, 2.8973, 3.7525, 2.8973] # all joints (with 3rd joint (1-indexed)): [2.8973, 1.7628, 2.8973, -0.0698, 2.8973, 3.7525, 2.8973]
active_joint_min: [-2.8973, -1.7628, -3.0718, -2.8973, -0.0175, -2.8973] # [-2.8973, -1.7628, -2.8973, -3.0718, -2.8973, -0.0175, -2.8973]

passive_base_pose: [0.15, 0.1, 1.4, 1, 0, 0, 0] # x y z, euler x y z
passive_q: [-2.89089697, -0.9754231 , -2.08760543, -1.08786023,  0.14448669, -0.26559232]
passive_urdf: "assets/urdf/human_arm/arm_6dof_continuous.urdf"
# passive_urdf: "assets/urdf/human_arm/arm.urdf" # 4dof

wheelchair_pose: [0.0, 0.0, 0.0, 0, 0, 0] # x y z, euler x y z
wheelchair_urdf: "assets/urdf/wheelchair/wheelchair.urdf"

# rotates active ee into passive ee, both in world frame: p_ee = R * a_ee
active_ee_to_passive_ee: [[0, 0, -1], [0, -1, 0], [-1, 0, 0]]
